version: "3.9"
services:
  # ------------------------------------------------------------------------------------
  # PostgreSQL database container
  # ------------------------------------------------------------------------------------
  postgres:
    container_name: postgres
    image: postgres:latest
    hostname: postgres
    ports:
      - "${POSTGRES_EXPOSED_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  # ------------------------------------------------------------------------------------
  # Node GraphQL - Prisma API container
  # ------------------------------------------------------------------------------------
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/dev/api/Dockerfile
    command: sh -c './generated/wait-for postgres:5432 -- npm run dev'
    depends_on:
      - postgres
    stdin_open: true
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
      - app-generated:/app/generated
      - /app/node_modules/
    ports:
      - "${PRISMA_API_EXPOSED_PORT}:4000"
    restart: unless-stopped

  # ------------------------------------------------------------------------------------
  # Prisma studio DB admin container
  # ------------------------------------------------------------------------------------
  database-admin:
    container_name: database-admin
    build:
      dockerfile: ./docker/dev/database-admin/Dockerfile
      context: .
    depends_on:
      - api
    environment:
      - POSTGRES_URL=${DATABASE_URL}
    restart: unless-stopped
    ports:
      - "${PRISMA_STUDIO_EXPOSED_PORT}:5555"

volumes:
  postgres-data:
  app-generated:
